# Generated by Django 4.2.6 on 2023-10-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newRegistrationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.CharField(max_length=200, unique=True)),
                ('student_phno', models.CharField(max_length=200, unique=True)),
                ('student_gender', models.CharField(max_length=200)),
                ('student_dob', models.CharField(max_length=200)),
                ('student_pwd', models.CharField(max_length=200)),
            ],
        ),
    ]
