# Generated by Django 4.2.6 on 2023-10-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmission', '0002_newregistrationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistrationuser',
            name='student_dob',
            field=models.DateField(),
        ),
    ]
