# Generated by Django 4.2.6 on 2023-10-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmission', '0003_alter_newregistrationuser_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistrationuser',
            name='student_phno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
