# Generated by Django 4.2.6 on 2023-10-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmission', '0005_alter_newregistrationuser_student_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='newRegistrationstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.CharField(max_length=200, unique=True)),
                ('student_phno', models.CharField(max_length=200, unique=True)),
                ('student_gender', models.CharField(max_length=200)),
                ('student_dob', models.DateField()),
                ('student_pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='registratedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='alreadyRegistration',
        ),
        migrations.DeleteModel(
            name='newRegistrationUser',
        ),
    ]
