# Generated by Django 4.2.6 on 2023-10-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAdmission', '0006_newregistrationstudent_registratedstudent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registratedStudent',
        ),
    ]
